import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "506 Army Base Workshop Dashboard",
  description: "Generated by IIT Bhilai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className="antialiased" 
        style={{ fontFamily: "system-ui, sans-serif" }}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}